[package]
name = "blockchain_wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = "0.14.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
rust-crypto = "0.2"
